### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by yachub**
I started a new branch off of master, rebased on branch feature_version2, then made my changes. If you have different preference for the work flow, then please let me know. I went ahead and addressed issues #2, #3, #4, & #6.

For #2, I realized you already added the dependency, however would it be correct to remove this? Reason being is because the Veeam [documentation](https://www.veeam.com/veeam_agent_windows_2_0_user_guide_pg.pdf) on page 77 states that it should install all dependencies automatically, including `Microsoft .NET Framework 4.5.2`, `Microsoft SQL Server 2012 Management Objects`, & `Microsoft SQL Server System CLR Types`.

For #3, I added the icon extracted from the installer itself and followed the [Package icon guidelines](https://github.com/chocolatey/choco/wiki/CreatePackages#package-icon-guidelines).

For #4, I simply added the checksum of the zip.

For #6, what do you think of changing the package name to simply "veeam-agent" to align with the rebranding of the package? I copied and paster the summary and description form the Veeam [site](https://www.veeam.com/windows-endpoint-server-backup-free.html)

The only other problem I ran into was that the install fails with a generic error code `1001` if there is a pending reboot. It looks like this type of error checking is not yet built into chocolatey itself.

Please let me know there's any additional or reverting of changes you would like to see.

Thanks,
Jake

### CODE REVIEW

**Comment by ericjaystevens** [comment]
Your comments look right on track with my thoughts, I actually stopped working on it after I could not solve the 1001 return code issue. Chocolatey.org build fails because the automated test environment environment is pending a reboot. I'll review your code as soon as I can, and probably just add 1001 and an acceptable return code so that I can push the package to choclatey.org.

**Comment by yachub** [comment]
Awesome, thanks! And wow, the pending reboot in their environment is definitely interesting, surely others have run into this issue frequently as well. I'll try to look into a way around it or fix for it though too.

Although, just thinking out loud here, Im not sure if adding 1001 as a `ValidExitCodes` to the install script would work very well because then user's would think it installed successfully (as well as chocolatey itself?), which may end up being very confusing.

**Comment by yachub** [comment]
I hopped on [gitter](https://gitter.im/chocolatey/choco) and asked this question, one member replied:

_that's when you request an exemption on the package review. Head there and mention why and a moderator will grab it when they get to it in the queue_ 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Review by ericjaystevens — APPROVED** [review]

**Comment by ericjaystevens** [comment]
Thanks for you contributions and suggestion to ask for an override to the chocolatey.org automated testing.

**Pull request merged**
